---
# Set the context path for the application.
#server:
#  contextPath: /omar-eureka-server

spring:
  application:
    name: omar-eureka-server
eureka:
  server:
    enableSelfPreservation: false
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      registerWithEureka: false
      fetchRegistry: false
